version: "3"
services:
  bitcoind:
    container_name: bitcoind
    privileged: true
    image: oneforalonee/bitcoind:v26.0
    restart: on-failure
    hostname: bitcoind
    stop_grace_period: 5m
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    command: >-
      bitcoind -server=1 -testnet=1
      -zmqpubrawblock=tcp://0.0.0.0:28334
      -zmqpubrawtx=tcp://0.0.0.0:28335 -zmqpubhashblock=tcp://0.0.0.0:28336
      -txindex=1 -rpcbind=0.0.0.0 -rpcallowip=0.0.0.0/0
      -rpcport=18332 -rest -listen=1 -listenonion=0
      -rpcauth=alice:128f22494cc2208ea8376a3d0b45a131$9cc0187c0e49f35454a3ed1250e40ecaef420cfcd294d3ac22496adbe64f04b9
    expose:
      - 8332
    ports:
      - 8332:8332
    volumes:
      - ./bitcoind:/home/bitcoin/.bitcoin

  electrs:
    depends_on:
      - bitcoind
    links:
      - bitcoind
    container_name: electrs
    privileged: true
    image: oneforalonee/electrs:latest
    restart: on-failure
    hostname: electrs
    command: >-
      /usr/bin/electrs --conf=/electrs/electrs.toml
    expose:
      - 50001
    ports:
      - 50001:50001
    volumes:
      - ./db:/electrs/db
      - ./electrs.toml:/electrs/electrs.toml
